spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Spotify_Project
    username: user
    password: user123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true