# Database configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Mail properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: demo.project006@gmail.com
    password: vaqo mplb sxqe axoe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  config:
    import: "optional:file:.env[.properties]"